### ISSUE TITLE
Какие требования для установки? 

### ISSUE THREAD

**Issue by goldwizard13** [tischmann/atlantis#1]
Какие требования для установки? php и тд
Есть ли возможность понизить версию php до 8.0?

**Comment by tischmann** [comment]
Целевая ОС: Lunux. Целевая СУБД: MySQL 8.0. Целевая версия PHP 8.2. Понизить до 8.0 в принципе возможно, но нужно учесть все нововведения от версий 8.1 и 8.2, их не много, но они имеются в коде.
